import { Convalidation } from "@/types/convalidation";

const convalidationData: Convalidation [] = [
  
    {
        id: 1,
        Sem_1: 'I',
        Curso_1: 'CE1102 Taller de Programación',
        Sem_2: 'I',
        Curso_2: 'CE1102 Fundamentos en Sistemas Computacionales',
    },
    {
        id: 2,
        Sem_1: 'II',
        Curso_1: 'QU1107 Química Básica II',
        Sem_2: 'VIII',
        Curso_2: 'Electiva',
    },
    {
        id: 3,
        Sem_1: 'VII',
        Curso_1: 'CE4101 Especificación y Diseño de Software',
        Sem_2: 'II',
        Curso_2: 'Principios de Modelado en Ingeniería',
    },
    {
        id: 4,
        Sem_1: 'II',
        Curso_1: 'Principios de Modelado en Ingeniería',
        Sem_2: 'VII',
        Curso_2: 'CE4101 Especificación y Diseño de Software',
    },
    {
        id: 5,
        Sem_1: 'IV',
        Curso_1: 'FI2103 Física General III',
        Sem_2: 'VIII',
        Curso_2: 'Electiva',
    },
    {
        id: 6,
        Sem_1: 'IV',
        Curso_1: 'Paradigmas de Programación',
        Sem_2: 'V',
        Curso_2: 'CE3104 Lenguajes, Compiladores, Intérpretes',
    },
    {
        id: 7,
        Sem_1: 'V',
        Curso_1: 'CE3104 Lenguajes, Compiladores, Intérpretes',
        Sem_2: 'VI',
        Curso_2: 'Compiladores e Intérpretes',
    },
    {
        id: 8,
        Sem_1: 'V',
        Curso_1: 'EL3212 Circuitos Discretos ',
        Sem_2: 'VIII',
        Curso_2: 'Electiva',
    },
    {
        id: 9,
        Sem_1: 'V',
        Curso_1: 'FI2104 Física General IV',
        Sem_2: 'VIII',
        Curso_2: 'Electiva',
    },
    {
        id: 10,
        Sem_1: 'VII',
        Curso_1: 'ELxxxx Probabilidad y Estadística',
        Sem_2: 'V',
        Curso_2: 'PIxxxx Probabilidad y Estadística',
    },
    {
        id: 11,
        Sem_1: 'VI',
        Curso_1: 'EL3213 Circuitos Integrados Lineales',
        Sem_2: 'VI',
        Curso_2: 'Circuitos Analógicos',
    },
    {
        id: 12,
        Sem_1: 'VI',
        Curso_1: 'EL3310 Diseño de Circuitos Digitales',
        Sem_2: 'V',
        Curso_2: 'Fundamentos de Arquitectura',
    },
    {
        id: 13,
        Sem_1: 'VII',
        Curso_1: 'EL4701 Modelos de Sistemas',
        Sem_2: 'VI',
        Curso_2: 'Análisis de Señales Mixtas',
    },
    {
        id: 14,
        Sem_1: 'VII',
        Curso_1: 'CE4101 Especificación y Diseño de Software',
        Sem_2: 'VII',
        Curso_2: 'Diseño y Calidad de Productos Tecnológicos',
    },
    {
        id: 15,
        Sem_1: 'VII',
        Curso_1: 'CE4202 Taller de Diseño Analógico',
        Sem_2: 'VII',
        Curso_2: 'Taller de Señal Mixta',
    },
    {
        id: 16,
        Sem_1: 'VIII',
        Curso_1: 'Electiva - Introducción a Sistemas Embebidos',
        Sem_2: 'VIII',
        Curso_2: 'Sistemas Empotrados',
    },
    {
        id: 17,
        Sem_1: 'VIII',
        Curso_1: 'CE4501 Electiva CE 1',
        Sem_2: 'VIII',
        Curso_2: 'Electiva CE 1',
    },
    {
        id: 18,
        Sem_1: 'VIII',
        Curso_1: 'Electivas',
        Sem_2: 'VIII',
        Curso_2: 'Electivas',
    },
    {
        id: 19,
        Sem_1: 'IX',
        Curso_1: 'CE5302 Proyecto de Diseño de Ingeniería en Computadores',
        Sem_2: 'IX',
        Curso_2: 'Proyecto de Aplicación de la Ingeniería en Computadores',
    },

];

export default convalidationData;